<?php
$title = 'Remover Pessoa';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<p>Deseja realmente excluir <?=$this->escapeHtml($pessoa->getNome());?></p>
<form  action="<?=$this->url('pessoa',['action'=>'remover','id'=>$id]);?>">
    <div class="form-group">
        <input type="hidden" name="id" value="<?=$id;?>">
        <input type="submit" class="btn btn-danger" name="del" value="Sim">
        <input type="submit" class="btn btn-success btn-lg" name='del' value="Não">
    </div>
</form>